// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Error.proto

package go_viewmodel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Error struct {
	ErrorMessage         string   `protobuf:"bytes,1,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_Error_ad782147cb7e3b5d, []int{0}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*Error)(nil), "prototype.Error")
}

func init() { proto.RegisterFile("Error.proto", fileDescriptor_Error_ad782147cb7e3b5d) }

var fileDescriptor_Error_ad782147cb7e3b5d = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x76, 0x2d, 0x2a, 0xca,
	0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0x53, 0x25, 0x95, 0x05, 0xa9, 0x4a,
	0x3a, 0x5c, 0xac, 0x60, 0x19, 0x21, 0x65, 0x2e, 0xde, 0x54, 0x10, 0x23, 0x3e, 0x37, 0xb5, 0xb8,
	0x38, 0x31, 0x3d, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x88, 0x07, 0x2c, 0xe8, 0x0b, 0x11,
	0x73, 0x32, 0xe1, 0x12, 0x4e, 0xce, 0xcf, 0xd5, 0x2b, 0xcb, 0x4c, 0xcf, 0x4b, 0x2d, 0xce, 0xd0,
	0x4b, 0x49, 0xcd, 0xcd, 0x4f, 0x2c, 0x28, 0x70, 0xe2, 0x05, 0x1b, 0x11, 0x94, 0x5a, 0x5c, 0x90,
	0x9f, 0x57, 0x9c, 0xea, 0xc1, 0x1c, 0xc5, 0x93, 0x9e, 0xaf, 0x5b, 0x96, 0x99, 0x5a, 0x9e, 0x9b,
	0x9f, 0x92, 0x9a, 0x93, 0xc4, 0x06, 0xb6, 0xce, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x42,
	0xbb, 0xe5, 0x84, 0x00, 0x00, 0x00,
}
