// Code generated by protoc-gen-go. DO NOT EDIT.
// source: UserViewModel.proto

package go_viewmodel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserViewModel struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserViewModel) Reset()         { *m = UserViewModel{} }
func (m *UserViewModel) String() string { return proto.CompactTextString(m) }
func (*UserViewModel) ProtoMessage()    {}
func (*UserViewModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_UserViewModel_bba5fab1ef3d58f3, []int{0}
}
func (m *UserViewModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserViewModel.Unmarshal(m, b)
}
func (m *UserViewModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserViewModel.Marshal(b, m, deterministic)
}
func (dst *UserViewModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserViewModel.Merge(dst, src)
}
func (m *UserViewModel) XXX_Size() int {
	return xxx_messageInfo_UserViewModel.Size(m)
}
func (m *UserViewModel) XXX_DiscardUnknown() {
	xxx_messageInfo_UserViewModel.DiscardUnknown(m)
}

var xxx_messageInfo_UserViewModel proto.InternalMessageInfo

func (m *UserViewModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*UserViewModel)(nil), "prototype.UserViewModel")
}

func init() { proto.RegisterFile("UserViewModel.proto", fileDescriptor_UserViewModel_bba5fab1ef3d58f3) }

var fileDescriptor_UserViewModel_bba5fab1ef3d58f3 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0e, 0x2d, 0x4e, 0x2d,
	0x0a, 0xcb, 0x4c, 0x2d, 0xf7, 0xcd, 0x4f, 0x49, 0xcd, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x04, 0x53, 0x25, 0x95, 0x05, 0xa9, 0x4a, 0xca, 0x5c, 0xbc, 0x28, 0x2a, 0x84, 0x84, 0xb8,
	0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x27, 0x1b,
	0x2e, 0xe1, 0xe4, 0xfc, 0x5c, 0xbd, 0xb2, 0xcc, 0xf4, 0xbc, 0xd4, 0xe2, 0x0c, 0xbd, 0x94, 0xd4,
	0xdc, 0xfc, 0xc4, 0x82, 0x02, 0x27, 0x51, 0x14, 0x9d, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5,
	0xa9, 0x1e, 0xcc, 0x51, 0x3c, 0xe9, 0xf9, 0xba, 0x65, 0x99, 0xa9, 0xe5, 0xb9, 0x20, 0xf1, 0x24,
	0x36, 0xb0, 0x6d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xc8, 0xe9, 0x65, 0x8b, 0x00,
	0x00, 0x00,
}
