// Objective-C API for talking to github.com/demo Go package.
//   gobind -lang=objc github.com/demo
//
// File is generated by gobind. Do not edit.

#ifndef __Demo_H__
#define __Demo_H__

@import Foundation;
#include "Universe.objc.h"


@class DemoUser;
@class DemoUserResponse;
@protocol DemoAPIResponse;
@class DemoAPIResponse;

@interface DemoUser : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (NSString*)firstName;
- (void)setFirstName:(NSString*)v;
- (NSString*)middleName;
- (void)setMiddleName:(NSString*)v;
- (NSString*)lastName;
- (void)setLastName:(NSString*)v;
- (NSString*)name;
- (void)setName:(NSString*)v;
@end

@interface DemoUserResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (DemoUser*)user;
- (void)setUser:(DemoUser*)v;
@end

@protocol DemoAPIResponse <NSObject>
- (void)onErrorResponse:(NSString*)err;
- (void)onSuccessResponse:(NSData*)response;
@end

FOUNDATION_EXPORT void DemoGetUserViewModel(id<DemoAPIResponse> mobileCallback);

@class DemoAPIResponse;

@interface DemoAPIResponse : NSObject <goSeqRefInterface, DemoAPIResponse> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)onErrorResponse:(NSString*)err;
- (void)onSuccessResponse:(NSData*)response;
@end

#endif
