// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Error.proto

package com.vignesh.demoapp;

public final class ErrorResponse {
  private ErrorResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ErrorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:prototype.Error)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string error_message = 1;</code>
     */
    java.lang.String getErrorMessage();
    /**
     * <code>string error_message = 1;</code>
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();
  }
  /**
   * Protobuf type {@code prototype.Error}
   */
  public  static final class Error extends
      com.google.protobuf.GeneratedMessageLite<
          Error, Error.Builder> implements
      // @@protoc_insertion_point(message_implements:prototype.Error)
      ErrorOrBuilder {
    private Error() {
      errorMessage_ = "";
    }
    public static final int ERROR_MESSAGE_FIELD_NUMBER = 1;
    private java.lang.String errorMessage_;
    /**
     * <code>string error_message = 1;</code>
     */
    public java.lang.String getErrorMessage() {
      return errorMessage_;
    }
    /**
     * <code>string error_message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(errorMessage_);
    }
    /**
     * <code>string error_message = 1;</code>
     */
    private void setErrorMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errorMessage_ = value;
    }
    /**
     * <code>string error_message = 1;</code>
     */
    private void clearErrorMessage() {
      
      errorMessage_ = getDefaultInstance().getErrorMessage();
    }
    /**
     * <code>string error_message = 1;</code>
     */
    private void setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errorMessage_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!errorMessage_.isEmpty()) {
        output.writeString(1, getErrorMessage());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!errorMessage_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getErrorMessage());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.vignesh.demoapp.ErrorResponse.Error parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.vignesh.demoapp.ErrorResponse.Error parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.vignesh.demoapp.ErrorResponse.Error parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.vignesh.demoapp.ErrorResponse.Error parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.vignesh.demoapp.ErrorResponse.Error parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.vignesh.demoapp.ErrorResponse.Error parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.vignesh.demoapp.ErrorResponse.Error parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.vignesh.demoapp.ErrorResponse.Error parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.vignesh.demoapp.ErrorResponse.Error parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.vignesh.demoapp.ErrorResponse.Error parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.vignesh.demoapp.ErrorResponse.Error parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.vignesh.demoapp.ErrorResponse.Error parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.vignesh.demoapp.ErrorResponse.Error prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code prototype.Error}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.vignesh.demoapp.ErrorResponse.Error, Builder> implements
        // @@protoc_insertion_point(builder_implements:prototype.Error)
        com.vignesh.demoapp.ErrorResponse.ErrorOrBuilder {
      // Construct using com.vignesh.demoapp.ErrorResponse.Error.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string error_message = 1;</code>
       */
      public java.lang.String getErrorMessage() {
        return instance.getErrorMessage();
      }
      /**
       * <code>string error_message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        return instance.getErrorMessageBytes();
      }
      /**
       * <code>string error_message = 1;</code>
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        copyOnWrite();
        instance.setErrorMessage(value);
        return this;
      }
      /**
       * <code>string error_message = 1;</code>
       */
      public Builder clearErrorMessage() {
        copyOnWrite();
        instance.clearErrorMessage();
        return this;
      }
      /**
       * <code>string error_message = 1;</code>
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setErrorMessageBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:prototype.Error)
    }
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.vignesh.demoapp.ErrorResponse.Error();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.vignesh.demoapp.ErrorResponse.Error other = (com.vignesh.demoapp.ErrorResponse.Error) arg1;
          errorMessage_ = visitor.visitString(!errorMessage_.isEmpty(), errorMessage_,
              !other.errorMessage_.isEmpty(), other.errorMessage_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  java.lang.String s = input.readStringRequireUtf8();

                  errorMessage_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.vignesh.demoapp.ErrorResponse.Error.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:prototype.Error)
    private static final com.vignesh.demoapp.ErrorResponse.Error DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Error();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.vignesh.demoapp.ErrorResponse.Error getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Error> PARSER;

    public static com.google.protobuf.Parser<Error> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
